

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/shared/NavBar";
import Footer from "@/Components/shared/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HireLoop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    data-theme="dark"
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <main className="flex-1 flex flex-col">
          <NavBar/>
        {children}
        </main>
        <Footer/>
        <ToastContainer/>
      </body>
      
    </html>
  );
}
